[project]
name = "leetcode-fun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pytest>=8.4.2",
    "rich>=14.1.0",
    "typer>=0.17.4",
]
